### ISSUE TITLE
请问此方法和用homekit反向接入有什么区别？

### ISSUE THREAD

**Issue by qy19920913** [niceboygithub/AqaraGateway#190]
如果有条件homekit反向接入 还需要去刷机吗？

**Comment by niceboygithub** [comment]
If you have door locker, pet feeder, you can get status of them when using HomeKit bridge.

Another, the power info of plug is also missing when using HomeKit bridge.

**Comment by tomky** [comment]
I wonder if this approach can expose wireless buttons to HomeKit? 

For now, the wall switches which manually changed to wireless button mode in Aqara home will not be exposed to HomeKit. Does this approach make differences here?

**Comment by niceboygithub** [comment]
AqaraGateway is better than using HomeKit Bridge to integrate HA. More functions are from AqaraGateway

**Comment by tomky** [comment]
我想知道有哪些額外功能呢？像是我在Aqara Home裡把有線開關改無線開關，改後的無線開關在HomeKit裡看不到，只能看到本來的有線開關。那麼走AqaraGateway的話可以在HA裡看到嗎？

**Comment by Necroneco** [comment]
> 我想知道有哪些額外功能呢？像是我在Aqara Home裡把有線開關改無線開關，改後的無線開關在HomeKit裡看不到，只能看到本來的有線開關。那麼走AqaraGateway的話可以在HA裡看到嗎？

可以的，你可以查看开关的 `binary_sensor.xxxxxxxxxxxxxxxx_switch`，按下的时候，它会有变化。

你可以在自动化里尝试监听这种触发条件：
```yaml
platform: event
event_type: xiaomi_aqara.click
event_data:
  entity_id: binary_sensor.xxxxxxxxxxxxxxxx_switch
  click_type: button_1_single
```
